version: '3.8'

services:
  mariadb:
    container_name: mariadb-container
    image: mariadb
    build: ./requirements/mariadb
    env_file: ./.env
    expose:
      - "3306"
    networks:
      - docker-network
    volumes:
      - mariadb-volume:/var/lib/mysql/
    restart: unless-stopped

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress-container
    image: wordpress
    build: ./requirements/wordpress
    env_file: ./.env
    networks: 
      - docker-network
    expose:
      - "9000"
    volumes:
      - wordpress-volume:/var/www/html/
    restart: unless-stopped

  nginx:
    depends_on:
      - wordpress
    container_name: nginx-container
    image: nginx
    build: ./requirements/nginx
    env_file: ./.env
    networks:
      - docker-network
    expose:
      - "9000"
    ports:
      - 443:443
    volumes:
      - wordpress-volume:/var/www/html/
    restart: unless-stopped

networks:
  docker-network:
    name: docker-network

volumes:
  mariadb-volume:
    name: mariadb-volume
    driver: local
    driver_opts:
      type: none
      device: /home/tlouro-c/data/mariadb
      o: 'bind'
  wordpress-volume:
    name: wordpress-volume
    driver: local
    driver_opts:
      type: none
      device: /home/tlouro-c/data/wordpress
      o: 'bind'

